// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkYOYElqzzDR14NuyTzorM8VxtJGUK9yc',
    appId: '1:464434589023:web:473d66fd0b71531282daea',
    messagingSenderId: '464434589023',
    projectId: 'homes-6390b',
    authDomain: 'homes-6390b.firebaseapp.com',
    storageBucket: 'homes-6390b.appspot.com',
    measurementId: 'G-7V7LKHZMRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD6cciLODJPo7uCEDGMRgrOgQsg9iTu1E',
    appId: '1:464434589023:android:fdce4eca56fff55a82daea',
    messagingSenderId: '464434589023',
    projectId: 'homes-6390b',
    storageBucket: 'homes-6390b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4vqLrEeOq0K6hHvt4z49lzKSZutn9MwU',
    appId: '1:464434589023:ios:0aeafd859ae55e9582daea',
    messagingSenderId: '464434589023',
    projectId: 'homes-6390b',
    storageBucket: 'homes-6390b.appspot.com',
    iosBundleId: 'com.example.SummitHomes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4vqLrEeOq0K6hHvt4z49lzKSZutn9MwU',
    appId: '1:464434589023:ios:0aeafd859ae55e9582daea',
    messagingSenderId: '464434589023',
    projectId: 'homes-6390b',
    storageBucket: 'homes-6390b.appspot.com',
    iosBundleId: 'com.example.SummitHomes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkYOYElqzzDR14NuyTzorM8VxtJGUK9yc',
    appId: '1:464434589023:web:18792462880fce1482daea',
    messagingSenderId: '464434589023',
    projectId: 'homes-6390b',
    authDomain: 'homes-6390b.firebaseapp.com',
    storageBucket: 'homes-6390b.appspot.com',
    measurementId: 'G-Z0RKVWQR4C',
  );
}
